sudo: false
language: go
go:
  - "1.6"
  - "tip"
env:
  - EVM_EMACS=emacs-24.4-travis
  - EVM_EMACS=emacs-24.5-travis
  - EVM_EMACS=emacs-25.1-travis
before_install:
  - go get -u golang.org/x/tools/cmd/godoc
  - export PATH=$HOME/gopath/bin:$PATH
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
  - evm install $EVM_EMACS --use --skip
  - cask
script:
  - go version
  - make test
